### ISSUE TITLE
Filter TinyMCE plugins

### ISSUE THREAD

**Issue by corvannoorloos** [swissspidy/disable-embeds#1]
Hello,

If I understand correct, should this
https://github.com/swissspidy/disable-embeds/blob/master/disable-embeds.php#L40
```php
add_action( 'tiny_mce_plugins', 'disable_embeds_tiny_mce_plugin' );
```
be this?
```php
add_filter( 'tiny_mce_plugins', 'disable_embeds_tiny_mce_plugin' );
```

**Comment by swissspidy** [comment]
These functions do exactly the same, so it works anyway. You're right though, using add_filter makes it more clear for people :)

After the recent changes in trunk I need to update some parts anyway, like disabling the REST API endpoint.
