### ISSUE TITLE
Embeds from own site are still shown and broken

### ISSUE THREAD

**Issue by rmens** [swissspidy/disable-embeds#2]
After installing the plugin and enabling it, links to the site itself that are placed in links or a bbpress forum, are still showing up and broken because the ```/embed/``` has been removed by this plugin. It should also remove embeds from the own domain.

![schermafbeelding 2016-07-10 om 19 37 44](https://cloud.githubusercontent.com/assets/6742496/16715045/de488180-46d5-11e6-92bb-2d09d7c0b097.png)

**Comment by swissspidy** [comment]
Thanks for your report and the screenshot!

Are you by chance running WordPress 4.5.3 and did it work on let's say WordPress 4.5.0?

Also regarding the screenshot, did you add the embed before or after activating the plugin?

**Comment by rmens** [comment]
We are running Wordpress 4.5.3 and I'm 98% sure it did work before. The plugin was already active while adding the embed (it has been installed since months)

**Comment by swissspidy** [comment]
OK, cool, good to know!

We added some changes to embeds in 4.5.3 and 4.6 that might need adjustment in the plugin. I'll try to fix it next week.

**Comment by swissspidy** [comment]
I published version 1.3.0 of the plugin to the WordPress.org plugin directory now. It removes that extra filter added in WordPress 4.5.3. You should get an update notice in your WordPress dashboard soon.

Thanks again for your help!
